'use strict';
const uuid = require('uuid');
const moment = require('moment');

/** @type {import('sequelize-cli').Migration} */

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Cattle', [
      {
        id: uuid.v4(),
        serial_code: 'A1C23',
        age: 13,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C24',
        age: 20,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C25',
        age: 15,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C26',
        age: 16,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C27',
        age: 20,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C28',
        age: 21,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C29',
        age: 22,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C30',
        age: 23,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C40',
        age: 14,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C41',
        age: 15,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C42',
        age: 16,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C43',
        age: 17,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C55',
        age: 18,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C23',
        age: 21,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C003',
        age: 27,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C783',
        age: 17,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C30',
        age: 8,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C03',
        age: 7,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C63',
        age: 8,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C73',
        age: 25,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C83',
        age: 24,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A2C53',
        age: 10,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A1C99',
        age: 19,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A3C12',
        age: 17,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A5C45',
        age: 11,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A7C23',
        age: 12,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A7C00',
        age: 3,
        gender: 'M',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Good',
        status: 'Active',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A8C99',
        age: 23,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Bad',
        status: 'Inactive',
        utilization: 80,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
      {
        id: uuid.v4(),
        serial_code: 'A0C23',
        age: 24,
        gender: 'F',
        farm: 'Ludhiana',
        ownerId: '952e9820-882a-42e9-bd64-cb8da0b25c30',
        health: 'Bad',
        status: 'Inactive',
        utilization: 50,
        deletedAt: null,
        createdAt: moment().format(),
        updatedAt: moment().format(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Cattle', null, {});
  },
};
